FROM eclipse-temurin:19.0.2_7-jdk-focal
MAINTAINER boy.iit@gmail.com
COPY target/moviesearch-java-1.0.0-SNAPSHOT.jar  moviesearch-java-1.0.0-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/moviesearch-java-1.0.0-SNAPSHOT.jar"]
